export const CHANGE_MEETING_TAB = 'meeting/CHANGE_MEETING_TAB'
export const CHANGE_MEETING_LIST = 'meeting/CHANGE_MEETING_LIST'
export const CHANGE_MEETING_ENTER_LOADING = 'meeting/CHANGE_MEETING_ENTER_LOADING'
